-- Tenant and integration tables

CREATE TABLE "Tenant" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "code" text NOT NULL,
  "portalUrl" text NOT NULL,
  "websiteUrl" text,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("code")
);

CREATE TABLE "ExternalIntegration" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenantId" uuid NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "websiteBaseUrl" text NOT NULL,
  "apiKeyHash" text NOT NULL,
  "apiSecretEncrypted" jsonb NOT NULL,
  "webhookSecretEncrypted" jsonb,
  "shopApiEnabled" boolean NOT NULL DEFAULT true,
  "webhookEnabled" boolean NOT NULL DEFAULT false,
  "webhookTargetUrl" text,
  "lastApiCallAt" timestamptz,
  "lastWebhookSentAt" timestamptz,
  "lastCatalogSyncAt" timestamptz,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "ExternalIntegration_tenantId_idx" ON "ExternalIntegration"("tenantId");

CREATE TABLE "ExternalIntegrationKey" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "integrationId" uuid NOT NULL REFERENCES "ExternalIntegration"("id") ON DELETE CASCADE,
  "keyHash" text NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "revokedAt" timestamptz
);
CREATE INDEX "ExternalIntegrationKey_integrationId_idx" ON "ExternalIntegrationKey"("integrationId");

CREATE TABLE "ApiRequestLog" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenantId" uuid NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,
  "integrationId" uuid NOT NULL REFERENCES "ExternalIntegration"("id") ON DELETE CASCADE,
  "endpoint" text NOT NULL,
  "method" text NOT NULL,
  "statusCode" integer NOT NULL,
  "latencyMs" integer NOT NULL,
  "ipAddress" text,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "ApiRequestLog_tenantId_idx" ON "ApiRequestLog"("tenantId");
CREATE INDEX "ApiRequestLog_integrationId_idx" ON "ApiRequestLog"("integrationId");

CREATE TABLE "WebhookDelivery" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenantId" uuid NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,
  "integrationId" uuid NOT NULL REFERENCES "ExternalIntegration"("id") ON DELETE CASCADE,
  "eventType" text NOT NULL,
  "targetUrl" text NOT NULL,
  "payload" jsonb NOT NULL,
  "deliveryId" text NOT NULL,
  "attemptCount" integer NOT NULL DEFAULT 0,
  "lastStatusCode" integer,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "lastAttemptAt" timestamptz,
  UNIQUE ("deliveryId")
);
CREATE INDEX "WebhookDelivery_tenantId_idx" ON "WebhookDelivery"("tenantId");
CREATE INDEX "WebhookDelivery_integrationId_idx" ON "WebhookDelivery"("integrationId");

CREATE TABLE "Application" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenantId" uuid NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,
  "sequence" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "reference" text NOT NULL,
  "parentName" text NOT NULL,
  "parentEmail" text NOT NULL,
  "parentPhone" text,
  "studentName" text NOT NULL,
  "grade" text NOT NULL,
  "status" text NOT NULL DEFAULT 'Submitted',
  "source" text NOT NULL DEFAULT 'website',
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "Application_tenantId_idx" ON "Application"("tenantId");
CREATE UNIQUE INDEX "Application_reference_key" ON "Application"("reference");

CREATE TABLE "CrmLead" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenantId" uuid NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,
  "source" text NOT NULL,
  "name" text NOT NULL,
  "email" text NOT NULL,
  "phone" text,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "CrmLead_tenantId_idx" ON "CrmLead"("tenantId");

CREATE TABLE "StoreCategory" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "description" text,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "StoreProduct" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "categoryId" uuid,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "description" text,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY ("categoryId") REFERENCES "StoreCategory"("id") ON DELETE SET NULL
);
CREATE INDEX "StoreProduct_categoryId_idx" ON "StoreProduct"("categoryId");

CREATE TABLE "StoreVariant" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "productId" uuid NOT NULL REFERENCES "StoreProduct"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "sku" text NOT NULL UNIQUE,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "StoreVariant_productId_idx" ON "StoreVariant"("productId");

CREATE TABLE "StorePrice" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "variantId" uuid NOT NULL UNIQUE REFERENCES "StoreVariant"("id") ON DELETE CASCADE,
  "currency" text NOT NULL DEFAULT 'ZAR',
  "amount" double precision NOT NULL,
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "StoreStock" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "variantId" uuid NOT NULL UNIQUE REFERENCES "StoreVariant"("id") ON DELETE CASCADE,
  "quantity" integer NOT NULL,
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "StoreImage" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "productId" uuid NOT NULL REFERENCES "StoreProduct"("id") ON DELETE CASCADE,
  "url" text NOT NULL,
  "altText" text,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "StoreImage_productId_idx" ON "StoreImage"("productId");

CREATE TABLE "EmailOutbox" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "to" text NOT NULL,
  "subject" text NOT NULL,
  "body" text NOT NULL,
  "status" text NOT NULL DEFAULT 'PENDING',
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "sentAt" timestamptz,
  "error" text
);
