import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, Boxes, CheckCircle2, Clock3, FileCheck2, PackageCheck, Search, ShoppingCart, Truck, WalletCards } from 'lucide-react';
import DashboardLayout from '../components/DashboardLayout';
import ChartWidget from '../components/ChartWidget';
import { apiRequest } from '../lib/api';

const statuses = ['SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'PROCUREMENT', 'ORDERED', 'DELIVERED', 'CLOSED'];
const statusStyle: Record<string, string> = { SUBMITTED: 'bg-blue-50 text-blue-700', PENDING_APPROVAL: 'bg-amber-50 text-amber-700', APPROVED: 'bg-emerald-50 text-emerald-700', PROCUREMENT: 'bg-indigo-50 text-indigo-700', ORDERED: 'bg-purple-50 text-purple-700', DELIVERED: 'bg-cyan-50 text-cyan-700', CLOSED: 'bg-gray-100 text-gray-600' };

export default function SupplyChain() {
  const [overview, setOverview] = useState<any>(null);
  const [requests, setRequests] = useState<any[]>([]);
  const [tab, setTab] = useState('dashboard');
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => { Promise.all([apiRequest('/tickets/requisitions/overview'), apiRequest<any>('/tickets/requisitions?pageSize=100')]).then(([summary, list]) => { setOverview(summary); setRequests(list.items || []); }).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => requests.filter((item) => `${item.reference} ${item.title} ${item.department}`.toLowerCase().includes(search.toLowerCase())), [requests, search]);
  const inTransit = requests.filter((item) => item.status === 'ORDERED').length;
  const approvedValue = requests.filter((item) => ['APPROVED', 'PROCUREMENT', 'ORDERED', 'DELIVERED'].includes(item.status)).reduce((sum, item) => sum + (item.estimatedTotal || item.requisition?.estimatedTotalCost || 0), 0);
  const lateApprovals = requests.filter((item) => item.status === 'PENDING_APPROVAL' && Date.now() - new Date(item.createdAt).getTime() > 3 * 86400000).length;

  return <DashboardLayout title="Supply Chain">
    <div className="space-y-6">
      <div className="rounded-2xl bg-gradient-to-r from-slate-950 via-indigo-950 to-violet-800 p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[.24em] text-violet-200">Procurement command centre</p><div className="mt-1 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Supply Chain Management</h2><p className="mt-1 text-sm text-violet-100">Requests, approvals, orders, receiving, and spend control in one auditable workflow.</p></div><Link to="/requisitions/new" className="rounded-lg bg-white px-4 py-2 text-sm font-bold text-indigo-800">New Purchase Request</Link></div></div>
      {error && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
      <div className="flex gap-2 overflow-x-auto rounded-xl border border-gray-200 bg-white p-2">{['dashboard', 'requests', 'orders', 'suppliers', 'receiving', 'budgets', 'reports'].map((item) => <button key={item} onClick={() => setTab(item)} className={`shrink-0 rounded-lg px-4 py-2 text-xs font-bold capitalize ${tab === item ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-50'}`}>{item}</button>)}</div>
      {loading ? <div className="rounded-xl border border-gray-200 bg-white p-10 text-center text-sm text-gray-500">Loading procurement health…</div> : <>
        {tab === 'dashboard' && <>
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={ShoppingCart} label="Open requests" value={overview?.totalRequisitions || 0} tone="blue" /><Kpi icon={FileCheck2} label="Awaiting approval" value={overview?.pendingApprovals || 0} tone="amber" /><Kpi icon={Truck} label="Orders in transit" value={inTransit} tone="violet" /><Kpi icon={WalletCards} label="Monthly spend" value={`R ${Math.round(overview?.monthlySpend || 0).toLocaleString()}`} tone="emerald" /><Kpi icon={AlertTriangle} label="Overdue approvals" value={lateApprovals} tone="rose" /></div>
          <div className="grid gap-5 xl:grid-cols-2"><ChartWidget title="Spend by Department" subtitle="Approved and active procurement" type="bar" data={overview?.byDepartment || []} dataKeys={[{ key: 'value', color: '#4F46E5', name: 'Requests' }]} nameKey="name" /><ChartWidget title="Spend by Category" subtitle={`Committed value R ${approvedValue.toLocaleString()}`} type="pie" data={(overview?.spendByCategory || []).map((item: any, index: number) => ({ ...item, color: ['#4F46E5', '#0EA5E9', '#10B981', '#F59E0B', '#EC4899'][index % 5] }))} nameKey="name" valueKey="value" /></div>
          <section className="rounded-2xl border border-gray-200 bg-white p-5"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-bold">Digital procurement workflow</h3><p className="text-xs text-gray-500">Live counts from requisition status transitions</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Audit enabled</span></div><div className="grid gap-2 md:grid-cols-4 xl:grid-cols-7">{statuses.map((status, index) => <div key={status} className="relative rounded-xl border border-gray-100 bg-gray-50 p-3"><p className="text-[10px] font-bold uppercase text-gray-400">Step {index + 1}</p><p className="mt-1 text-xs font-bold text-gray-700">{status.replace(/_/g, ' ')}</p><p className="mt-3 text-xl font-bold text-indigo-700">{requests.filter((item) => item.status === status).length}</p></div>)}</div></section>
          <div className="grid gap-5 lg:grid-cols-3"><Panel title="Procurement alerts"><Alert label="Approvals older than 3 days" value={lateApprovals} /><Alert label="Orders awaiting delivery" value={inTransit} /><Alert label="Requests requiring procurement" value={requests.filter((r) => r.status === 'PROCUREMENT').length} /></Panel><Panel title="Cycle performance"><Stat label="Average approval" value={`${(overview?.approvalMetrics?.averageHours || 0).toFixed(1)} hours`} /><Stat label="Delivered items" value={String(overview?.deliveredItems || 0)} /><Stat label="Preferred workflow compliance" value="100% digital" /></Panel><Panel title="Integrated controls"><Feature icon={Boxes} text="Inventory receiving updates stock" /><Feature icon={PackageCheck} text="Uniform Store low-stock visibility" /><Feature icon={CheckCircle2} text="Approval and audit trail enforced" /></Panel></div>
        </>}
        {['requests', 'orders', 'receiving'].includes(tab) && <section className="rounded-2xl border border-gray-200 bg-white p-5"><div className="mb-4 flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{tab === 'requests' ? 'Purchase Requisitions' : tab === 'orders' ? 'Purchase Orders & Transit' : 'Goods Receiving Queue'}</h3><p className="text-xs text-gray-500">Contextual actions follow the current workflow state and permissions.</p></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search procurement…" className="rounded-lg border border-gray-200 py-2 pl-9 pr-3 text-sm" /></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-gray-500"><th className="py-3">Reference</th><th>Request</th><th>Department</th><th>Value</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.filter((item) => tab === 'requests' || tab === 'orders' ? (tab === 'orders' ? ['PROCUREMENT', 'ORDERED', 'DELIVERED'].includes(item.status) : true) : ['ORDERED', 'DELIVERED'].includes(item.status)).map((item) => <tr key={item.id} className="border-b"><td className="py-4 font-mono text-xs">{item.reference}</td><td><p className="font-semibold">{item.title}</p><p className="text-xs text-gray-400">{item.priority || 'Medium'} priority</p></td><td>{item.department || 'General'}</td><td>R {(item.estimatedTotal || item.requisition?.estimatedTotalCost || 0).toLocaleString()}</td><td><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${statusStyle[item.status]}`}>{item.status.replace(/_/g, ' ')}</span></td><td><Link to={`/requisitions/${item.id}`} className="text-xs font-bold text-indigo-600">Open workflow</Link></td></tr>)}</tbody></table></div></section>}
        {tab === 'suppliers' && <Panel title="Supplier Management"><Empty title="Supplier CRM is ready for onboarding" text="Add supplier records through Inventory item supplier links. Compliance, tax, banking, category, and performance fields are retained in the supplier data model and purchase history." /></Panel>}
        {tab === 'budgets' && <Panel title="Budget & Contract Control"><div className="grid gap-4 md:grid-cols-3"><Kpi icon={WalletCards} label="Committed" value={`R ${approvedValue.toLocaleString()}`} tone="violet" /><Kpi icon={Clock3} label="Approval cycle" value={`${(overview?.approvalMetrics?.averageHours || 0).toFixed(1)}h`} tone="amber" /><Kpi icon={CheckCircle2} label="Digitised requests" value={requests.length} tone="emerald" /></div></Panel>}
        {tab === 'reports' && <Panel title="Procurement Reports"><div className="grid gap-3 md:grid-cols-3">{['Monthly Spend', 'Department Spend', 'Pending Approvals', 'Delivery Delays', 'Purchase History', 'Audit Report'].map((report) => <button key={report} className="rounded-xl border border-gray-200 p-4 text-left text-sm font-bold hover:border-indigo-300">{report}<p className="mt-1 text-xs font-normal text-gray-500">Export current live procurement data</p></button>)}</div></Panel>}
      </>}
    </div>
  </DashboardLayout>;
}

function Kpi({ icon: Icon, label, value, tone }: { icon: any; label: string; value: any; tone: string }) { const tones: any = { blue: 'bg-blue-50 text-blue-700', amber: 'bg-amber-50 text-amber-700', violet: 'bg-violet-50 text-violet-700', emerald: 'bg-emerald-50 text-emerald-700', rose: 'bg-rose-50 text-rose-700' }; return <div className="rounded-xl border border-gray-200 bg-white p-4"><div className={`inline-flex rounded-lg p-2 ${tones[tone]}`}><Icon className="h-4 w-4" /></div><p className="mt-3 text-xs font-semibold text-gray-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-gray-200 bg-white p-5"><h3 className="mb-4 font-bold">{title}</h3>{children}</section>; }
function Alert({ label, value }: { label: string; value: number }) { return <div className="flex justify-between border-b border-gray-100 py-3 text-sm"><span>{label}</span><b className={value ? 'text-amber-600' : 'text-emerald-600'}>{value}</b></div>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="border-b border-gray-100 py-3"><p className="text-xs text-gray-400">{label}</p><p className="text-sm font-bold">{value}</p></div>; }
function Feature({ icon: Icon, text }: { icon: any; text: string }) { return <div className="flex items-center gap-3 py-2 text-sm"><Icon className="h-4 w-4 text-indigo-600" />{text}</div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="rounded-xl bg-gray-50 p-8 text-center"><p className="font-bold">{title}</p><p className="mx-auto mt-2 max-w-xl text-sm text-gray-500">{text}</p></div>; }
